### PR TITLE
feat: switch hosting to Fleek

### PR DESCRIPTION
**Pull request by lidel**
This PR does the minimal refactor to reuse DNSLink hosting and asset pinning provided by Fleek.

### CODE REVIEW

**Comment by lidel** [comment]
@RangerMauve  I tweaked constants so `URL_IPNS_MEDIA` uses URL with `/files/` suffix –  I suspect this introduces some false-negatives in Agregore-Browser-1.0.0-33 – I tested CID produced by fleek (`ipfs://bafybeihr3ackavi2gbjyqabb4y7uv2tlccltyocktnnxl236m45mpnqhfi`)  and some things fail–  due to origin change, it seems?

>

**Review by RangerMauve — APPROVED** [review]
This looks perfect! The errors you're seeing in Agregore are actually caused by raw CIDs not being supported for files in the latest release.

I'm planning to release the latest version on `master` this week so it should fix that issue.

**Comment by RangerMauve** [comment]
I'm having a bit of an issue with the new fleek IPNS URLs. It doesn't seem to be resolving with the latest version of js-ipfs-core. 🤔

**Comment by RangerMauve** [comment]
NVM, just tried to load the root IPNS domain and everything is working fine. 😁

image

**Pull request merged**
